// Copyright (c) 2017 Sony Corporation. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// *WARNING*
// THIS FILE IS AUTO-GENERATED BY CODE GENERATOR.
// PLEASE DO NOT EDIT THIS FILE BY HAND!

#include "Validation_inference.h"

#include <nnablart/functions.h>
#include <string.h>

typedef struct {
    void *buffer_pool[2];
    void *param_pool[16];
    rt_buffer_allocate_type_t variable_buffers_allocate_type[27];

    // Variables
    rt_variable_t v0; ///< x
    int v0_shape[4];
    rt_variable_t v1; ///< cnn/conv1/conv/W
    int v1_shape[4];
    rt_variable_t v2; ///< cnn/conv1/conv/b
    int v2_shape[1];
    rt_variable_t v3; ///< Convolution_Output
    int v3_shape[4];
    rt_variable_t v4; ///< cnn/conv1/bn/beta
    int v4_shape[4];
    rt_variable_t v5; ///< cnn/conv1/bn/gamma
    int v5_shape[4];
    rt_variable_t v6; ///< cnn/conv1/bn/mean
    int v6_shape[4];
    rt_variable_t v7; ///< cnn/conv1/bn/var
    int v7_shape[4];
    rt_variable_t v8; ///< BatchNormalization_Output
    int v8_shape[4];
    rt_variable_t v9; ///< Tanh_Output
    int v9_shape[4];
    rt_variable_t v10; ///< cnn/conv2/conv/W
    int v10_shape[4];
    rt_variable_t v11; ///< cnn/conv2/conv/b
    int v11_shape[1];
    rt_variable_t v12; ///< Convolution_2_Output
    int v12_shape[4];
    rt_variable_t v13; ///< cnn/conv2/bn/beta
    int v13_shape[4];
    rt_variable_t v14; ///< cnn/conv2/bn/gamma
    int v14_shape[4];
    rt_variable_t v15; ///< cnn/conv2/bn/mean
    int v15_shape[4];
    rt_variable_t v16; ///< cnn/conv2/bn/var
    int v16_shape[4];
    rt_variable_t v17; ///< BatchNormalization_2_Output
    int v17_shape[4];
    rt_variable_t v18; ///< Tanh_2_Output
    int v18_shape[4];
    rt_variable_t v19; ///< AveragePooling_Output
    int v19_shape[4];
    rt_variable_t v20; ///< cnn/fc3/affine/W
    int v20_shape[2];
    rt_variable_t v21; ///< cnn/fc3/affine/b
    int v21_shape[1];
    rt_variable_t v22; ///< Affine_Output
    int v22_shape[2];
    rt_variable_t v23; ///< Tanh_3_Output
    int v23_shape[2];
    rt_variable_t v24; ///< cnn/classifier/affine/W
    int v24_shape[2];
    rt_variable_t v25; ///< cnn/classifier/affine/b
    int v25_shape[1];
    rt_variable_t v26; ///< y
    int v26_shape[2];

    // Functions
    rt_function_t f0; ///< Convolution
    rt_variable_t* f0_inputs[3];
    rt_variable_t* f0_outputs[1];
    convolution_local_context_t *f0_local_context;
    int f0_local_context_shape_pad[2];
    int f0_local_context_shape_stride[2];
    int f0_local_context_shape_dilation[2];
    rt_function_t f1; ///< BatchNormalization
    rt_variable_t* f1_inputs[5];
    rt_variable_t* f1_outputs[1];
    batch_normalization_local_context_t *f1_local_context;
    int f1_local_context_shape_axes[1];
    rt_function_t f2; ///< Tanh
    rt_variable_t* f2_inputs[1];
    rt_variable_t* f2_outputs[1];
    rt_function_t f3; ///< Convolution
    rt_variable_t* f3_inputs[3];
    rt_variable_t* f3_outputs[1];
    convolution_local_context_t *f3_local_context;
    int f3_local_context_shape_pad[2];
    int f3_local_context_shape_stride[2];
    int f3_local_context_shape_dilation[2];
    rt_function_t f4; ///< BatchNormalization
    rt_variable_t* f4_inputs[5];
    rt_variable_t* f4_outputs[1];
    batch_normalization_local_context_t *f4_local_context;
    int f4_local_context_shape_axes[1];
    rt_function_t f5; ///< Tanh
    rt_variable_t* f5_inputs[1];
    rt_variable_t* f5_outputs[1];
    rt_function_t f6; ///< AveragePooling
    rt_variable_t* f6_inputs[1];
    rt_variable_t* f6_outputs[1];
    average_pooling_local_context_t *f6_local_context;
    int f6_local_context_shape_kernel[2];
    int f6_local_context_shape_stride[2];
    int f6_local_context_shape_pad[2];
    rt_function_t f7; ///< Affine
    rt_variable_t* f7_inputs[3];
    rt_variable_t* f7_outputs[1];
    affine_local_context_t *f7_local_context;
    rt_function_t f8; ///< Tanh
    rt_variable_t* f8_inputs[1];
    rt_variable_t* f8_outputs[1];
    rt_function_t f9; ///< Affine
    rt_variable_t* f9_inputs[3];
    rt_variable_t* f9_outputs[1];
    affine_local_context_t *f9_local_context;
} nnablart_validation_local_context_t;

int actual_buf_sizes[2] = {
    128,
    128,
};

void *(*rt_variable_malloc_func)(size_t size) = malloc;
void (*rt_variable_free_func)(void *ptr) = free;

void *(*rt_malloc_func)(size_t size) = malloc;
void (*rt_free_func)(void *ptr) = free;


void* nnablart_validation_allocate_context(void** params)
{
    nnablart_validation_local_context_t* c = malloc(sizeof(nnablart_validation_local_context_t));
    // Variable buffer
    for (int i = 0; i < 2; i++) {
        c->buffer_pool[i] = malloc(sizeof(float) * actual_buf_sizes[i]);
        memset(c->buffer_pool[i], 0, sizeof(float) * actual_buf_sizes[i]);
    }
    if(params) {
        c->variable_buffers_allocate_type[1] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[0] = *params++;
        c->variable_buffers_allocate_type[2] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[1] = *params++;
        c->variable_buffers_allocate_type[4] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[2] = *params++;
        c->variable_buffers_allocate_type[5] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[3] = *params++;
        c->variable_buffers_allocate_type[6] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[4] = *params++;
        c->variable_buffers_allocate_type[7] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[5] = *params++;
        c->variable_buffers_allocate_type[10] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[6] = *params++;
        c->variable_buffers_allocate_type[11] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[7] = *params++;
        c->variable_buffers_allocate_type[13] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[8] = *params++;
        c->variable_buffers_allocate_type[14] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[9] = *params++;
        c->variable_buffers_allocate_type[15] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[10] = *params++;
        c->variable_buffers_allocate_type[16] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[11] = *params++;
        c->variable_buffers_allocate_type[20] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[12] = *params++;
        c->variable_buffers_allocate_type[21] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[13] = *params++;
        c->variable_buffers_allocate_type[24] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[14] = *params++;
        c->variable_buffers_allocate_type[25] = RT_BUFFER_ALLOCATE_TYPE_ALLOCATED;
        c->param_pool[15] = *params++;
    } else {
        c->variable_buffers_allocate_type[1] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[0] = *params++;
        c->param_pool[0] = malloc(sizeof(float) * 36);
        c->variable_buffers_allocate_type[2] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[1] = *params++;
        c->param_pool[1] = malloc(sizeof(float) * 4);
        c->variable_buffers_allocate_type[4] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[2] = *params++;
        c->param_pool[2] = malloc(sizeof(float) * 4);
        c->variable_buffers_allocate_type[5] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[3] = *params++;
        c->param_pool[3] = malloc(sizeof(float) * 4);
        c->variable_buffers_allocate_type[6] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[4] = *params++;
        c->param_pool[4] = malloc(sizeof(float) * 4);
        c->variable_buffers_allocate_type[7] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[5] = *params++;
        c->param_pool[5] = malloc(sizeof(float) * 4);
        c->variable_buffers_allocate_type[10] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[6] = *params++;
        c->param_pool[6] = malloc(sizeof(float) * 288);
        c->variable_buffers_allocate_type[11] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[7] = *params++;
        c->param_pool[7] = malloc(sizeof(float) * 8);
        c->variable_buffers_allocate_type[13] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[8] = *params++;
        c->param_pool[8] = malloc(sizeof(float) * 8);
        c->variable_buffers_allocate_type[14] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[9] = *params++;
        c->param_pool[9] = malloc(sizeof(float) * 8);
        c->variable_buffers_allocate_type[15] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[10] = *params++;
        c->param_pool[10] = malloc(sizeof(float) * 8);
        c->variable_buffers_allocate_type[16] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[11] = *params++;
        c->param_pool[11] = malloc(sizeof(float) * 8);
        c->variable_buffers_allocate_type[20] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[12] = *params++;
        c->param_pool[12] = malloc(sizeof(float) * 512);
        c->variable_buffers_allocate_type[21] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[13] = *params++;
        c->param_pool[13] = malloc(sizeof(float) * 16);
        c->variable_buffers_allocate_type[24] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[14] = *params++;
        c->param_pool[14] = malloc(sizeof(float) * 80);
        c->variable_buffers_allocate_type[25] = RT_BUFFER_ALLOCATE_TYPE_MALLOC;
        c->param_pool[15] = *params++;
        c->param_pool[15] = malloc(sizeof(float) * 5);
    }

    // Variables
    // x
    (c->v0).type = NN_DATA_TYPE_FLOAT;
    (c->v0).shape.size = 4;
    c->v0_shape[0] = 1;
    c->v0_shape[1] = 1;
    c->v0_shape[2] = 8;
    c->v0_shape[3] = 8;
    (c->v0).shape.data = c->v0_shape;
    (c->v0).data = c->buffer_pool[0];
    // cnn/conv1/conv/W
    (c->v1).type = NN_DATA_TYPE_FLOAT;
    (c->v1).shape.size = 4;
    c->v1_shape[0] = 4;
    c->v1_shape[1] = 1;
    c->v1_shape[2] = 3;
    c->v1_shape[3] = 3;
    (c->v1).shape.data = c->v1_shape;
    (c->v1).data = c->param_pool[0];
    // cnn/conv1/conv/b
    (c->v2).type = NN_DATA_TYPE_FLOAT;
    (c->v2).shape.size = 1;
    c->v2_shape[0] = 4;
    (c->v2).shape.data = c->v2_shape;
    (c->v2).data = c->param_pool[1];
    // Convolution_Output
    (c->v3).type = NN_DATA_TYPE_FLOAT;
    (c->v3).shape.size = 4;
    c->v3_shape[0] = 1;
    c->v3_shape[1] = 4;
    c->v3_shape[2] = 4;
    c->v3_shape[3] = 4;
    (c->v3).shape.data = c->v3_shape;
    (c->v3).data = c->buffer_pool[1];
    // cnn/conv1/bn/beta
    (c->v4).type = NN_DATA_TYPE_FLOAT;
    (c->v4).shape.size = 4;
    c->v4_shape[0] = 1;
    c->v4_shape[1] = 4;
    c->v4_shape[2] = 1;
    c->v4_shape[3] = 1;
    (c->v4).shape.data = c->v4_shape;
    (c->v4).data = c->param_pool[2];
    // cnn/conv1/bn/gamma
    (c->v5).type = NN_DATA_TYPE_FLOAT;
    (c->v5).shape.size = 4;
    c->v5_shape[0] = 1;
    c->v5_shape[1] = 4;
    c->v5_shape[2] = 1;
    c->v5_shape[3] = 1;
    (c->v5).shape.data = c->v5_shape;
    (c->v5).data = c->param_pool[3];
    // cnn/conv1/bn/mean
    (c->v6).type = NN_DATA_TYPE_FLOAT;
    (c->v6).shape.size = 4;
    c->v6_shape[0] = 1;
    c->v6_shape[1] = 4;
    c->v6_shape[2] = 1;
    c->v6_shape[3] = 1;
    (c->v6).shape.data = c->v6_shape;
    (c->v6).data = c->param_pool[4];
    // cnn/conv1/bn/var
    (c->v7).type = NN_DATA_TYPE_FLOAT;
    (c->v7).shape.size = 4;
    c->v7_shape[0] = 1;
    c->v7_shape[1] = 4;
    c->v7_shape[2] = 1;
    c->v7_shape[3] = 1;
    (c->v7).shape.data = c->v7_shape;
    (c->v7).data = c->param_pool[5];
    // BatchNormalization_Output
    (c->v8).type = NN_DATA_TYPE_FLOAT;
    (c->v8).shape.size = 4;
    c->v8_shape[0] = 1;
    c->v8_shape[1] = 4;
    c->v8_shape[2] = 4;
    c->v8_shape[3] = 4;
    (c->v8).shape.data = c->v8_shape;
    (c->v8).data = c->buffer_pool[0];
    // Tanh_Output
    (c->v9).type = NN_DATA_TYPE_FLOAT;
    (c->v9).shape.size = 4;
    c->v9_shape[0] = 1;
    c->v9_shape[1] = 4;
    c->v9_shape[2] = 4;
    c->v9_shape[3] = 4;
    (c->v9).shape.data = c->v9_shape;
    (c->v9).data = c->buffer_pool[1];
    // cnn/conv2/conv/W
    (c->v10).type = NN_DATA_TYPE_FLOAT;
    (c->v10).shape.size = 4;
    c->v10_shape[0] = 8;
    c->v10_shape[1] = 4;
    c->v10_shape[2] = 3;
    c->v10_shape[3] = 3;
    (c->v10).shape.data = c->v10_shape;
    (c->v10).data = c->param_pool[6];
    // cnn/conv2/conv/b
    (c->v11).type = NN_DATA_TYPE_FLOAT;
    (c->v11).shape.size = 1;
    c->v11_shape[0] = 8;
    (c->v11).shape.data = c->v11_shape;
    (c->v11).data = c->param_pool[7];
    // Convolution_2_Output
    (c->v12).type = NN_DATA_TYPE_FLOAT;
    (c->v12).shape.size = 4;
    c->v12_shape[0] = 1;
    c->v12_shape[1] = 8;
    c->v12_shape[2] = 4;
    c->v12_shape[3] = 4;
    (c->v12).shape.data = c->v12_shape;
    (c->v12).data = c->buffer_pool[0];
    // cnn/conv2/bn/beta
    (c->v13).type = NN_DATA_TYPE_FLOAT;
    (c->v13).shape.size = 4;
    c->v13_shape[0] = 1;
    c->v13_shape[1] = 8;
    c->v13_shape[2] = 1;
    c->v13_shape[3] = 1;
    (c->v13).shape.data = c->v13_shape;
    (c->v13).data = c->param_pool[8];
    // cnn/conv2/bn/gamma
    (c->v14).type = NN_DATA_TYPE_FLOAT;
    (c->v14).shape.size = 4;
    c->v14_shape[0] = 1;
    c->v14_shape[1] = 8;
    c->v14_shape[2] = 1;
    c->v14_shape[3] = 1;
    (c->v14).shape.data = c->v14_shape;
    (c->v14).data = c->param_pool[9];
    // cnn/conv2/bn/mean
    (c->v15).type = NN_DATA_TYPE_FLOAT;
    (c->v15).shape.size = 4;
    c->v15_shape[0] = 1;
    c->v15_shape[1] = 8;
    c->v15_shape[2] = 1;
    c->v15_shape[3] = 1;
    (c->v15).shape.data = c->v15_shape;
    (c->v15).data = c->param_pool[10];
    // cnn/conv2/bn/var
    (c->v16).type = NN_DATA_TYPE_FLOAT;
    (c->v16).shape.size = 4;
    c->v16_shape[0] = 1;
    c->v16_shape[1] = 8;
    c->v16_shape[2] = 1;
    c->v16_shape[3] = 1;
    (c->v16).shape.data = c->v16_shape;
    (c->v16).data = c->param_pool[11];
    // BatchNormalization_2_Output
    (c->v17).type = NN_DATA_TYPE_FLOAT;
    (c->v17).shape.size = 4;
    c->v17_shape[0] = 1;
    c->v17_shape[1] = 8;
    c->v17_shape[2] = 4;
    c->v17_shape[3] = 4;
    (c->v17).shape.data = c->v17_shape;
    (c->v17).data = c->buffer_pool[1];
    // Tanh_2_Output
    (c->v18).type = NN_DATA_TYPE_FLOAT;
    (c->v18).shape.size = 4;
    c->v18_shape[0] = 1;
    c->v18_shape[1] = 8;
    c->v18_shape[2] = 4;
    c->v18_shape[3] = 4;
    (c->v18).shape.data = c->v18_shape;
    (c->v18).data = c->buffer_pool[0];
    // AveragePooling_Output
    (c->v19).type = NN_DATA_TYPE_FLOAT;
    (c->v19).shape.size = 4;
    c->v19_shape[0] = 1;
    c->v19_shape[1] = 8;
    c->v19_shape[2] = 2;
    c->v19_shape[3] = 2;
    (c->v19).shape.data = c->v19_shape;
    (c->v19).data = c->buffer_pool[1];
    // cnn/fc3/affine/W
    (c->v20).type = NN_DATA_TYPE_FLOAT;
    (c->v20).shape.size = 2;
    c->v20_shape[0] = 32;
    c->v20_shape[1] = 16;
    (c->v20).shape.data = c->v20_shape;
    (c->v20).data = c->param_pool[12];
    // cnn/fc3/affine/b
    (c->v21).type = NN_DATA_TYPE_FLOAT;
    (c->v21).shape.size = 1;
    c->v21_shape[0] = 16;
    (c->v21).shape.data = c->v21_shape;
    (c->v21).data = c->param_pool[13];
    // Affine_Output
    (c->v22).type = NN_DATA_TYPE_FLOAT;
    (c->v22).shape.size = 2;
    c->v22_shape[0] = 1;
    c->v22_shape[1] = 16;
    (c->v22).shape.data = c->v22_shape;
    (c->v22).data = c->buffer_pool[0];
    // Tanh_3_Output
    (c->v23).type = NN_DATA_TYPE_FLOAT;
    (c->v23).shape.size = 2;
    c->v23_shape[0] = 1;
    c->v23_shape[1] = 16;
    (c->v23).shape.data = c->v23_shape;
    (c->v23).data = c->buffer_pool[1];
    // cnn/classifier/affine/W
    (c->v24).type = NN_DATA_TYPE_FLOAT;
    (c->v24).shape.size = 2;
    c->v24_shape[0] = 16;
    c->v24_shape[1] = 5;
    (c->v24).shape.data = c->v24_shape;
    (c->v24).data = c->param_pool[14];
    // cnn/classifier/affine/b
    (c->v25).type = NN_DATA_TYPE_FLOAT;
    (c->v25).shape.size = 1;
    c->v25_shape[0] = 5;
    (c->v25).shape.data = c->v25_shape;
    (c->v25).data = c->param_pool[15];
    // y
    (c->v26).type = NN_DATA_TYPE_FLOAT;
    (c->v26).shape.size = 2;
    c->v26_shape[0] = 1;
    c->v26_shape[1] = 5;
    (c->v26).shape.data = c->v26_shape;
    (c->v26).data = c->buffer_pool[0];

    // Functions
    // Convolution
    c->f0_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f0).num_of_inputs = 3;
    (c->f0_inputs)[0] = &(c->v0);
    (c->f0_inputs)[1] = &(c->v1);
    (c->f0_inputs)[2] = &(c->v2);
    (c->f0).inputs = c->f0_inputs;
    (c->f0).num_of_outputs = 1;
    (c->f0_outputs)[0] = &(c->v3);
    (c->f0).outputs = c->f0_outputs;
    (c->f0).local_context = c->f0_local_context;
    (c->f0_local_context)->base_axis = 1;
    rt_list_t arg_f0_pad;
    arg_f0_pad.size = 2;
    arg_f0_pad.data = c->f0_local_context_shape_pad;
    arg_f0_pad.data[0] = 1;
    arg_f0_pad.data[1] = 1;
    (c->f0_local_context)->pad = arg_f0_pad;
    rt_list_t arg_f0_stride;
    arg_f0_stride.size = 2;
    arg_f0_stride.data = c->f0_local_context_shape_stride;
    arg_f0_stride.data[0] = 2;
    arg_f0_stride.data[1] = 2;
    (c->f0_local_context)->stride = arg_f0_stride;
    rt_list_t arg_f0_dilation;
    arg_f0_dilation.size = 2;
    arg_f0_dilation.data = c->f0_local_context_shape_dilation;
    arg_f0_dilation.data[0] = 1;
    arg_f0_dilation.data[1] = 1;
    (c->f0_local_context)->dilation = arg_f0_dilation;
    (c->f0_local_context)->group = 1;
    (c->f0_local_context)->channel_last = 0;
    allocate_convolution_local_context(&(c->f0));
    // BatchNormalization
    c->f1_local_context = malloc(sizeof(batch_normalization_local_context_t));
    (c->f1).num_of_inputs = 5;
    (c->f1_inputs)[0] = &(c->v3);
    (c->f1_inputs)[1] = &(c->v4);
    (c->f1_inputs)[2] = &(c->v5);
    (c->f1_inputs)[3] = &(c->v6);
    (c->f1_inputs)[4] = &(c->v7);
    (c->f1).inputs = c->f1_inputs;
    (c->f1).num_of_outputs = 1;
    (c->f1_outputs)[0] = &(c->v8);
    (c->f1).outputs = c->f1_outputs;
    (c->f1).local_context = c->f1_local_context;
    rt_list_t arg_f1_axes;
    arg_f1_axes.size = 1;
    arg_f1_axes.data = c->f1_local_context_shape_axes;
    arg_f1_axes.data[0] = 1;
    (c->f1_local_context)->axes = arg_f1_axes;
    (c->f1_local_context)->decay_rate = 0.8999999761581421;
    (c->f1_local_context)->eps = 9.999999747378752e-06;
    (c->f1_local_context)->batch_stat = 1;
    allocate_batch_normalization_local_context(&(c->f1));
    // Tanh
    (c->f2).num_of_inputs = 1;
    (c->f2_inputs)[0] = &(c->v8);
    (c->f2).inputs = c->f2_inputs;
    (c->f2).num_of_outputs = 1;
    (c->f2_outputs)[0] = &(c->v9);
    (c->f2).outputs = c->f2_outputs;
    (c->f2).local_context = 0;
    allocate_tanh_local_context(&(c->f2));
    // Convolution
    c->f3_local_context = malloc(sizeof(convolution_local_context_t));
    (c->f3).num_of_inputs = 3;
    (c->f3_inputs)[0] = &(c->v9);
    (c->f3_inputs)[1] = &(c->v10);
    (c->f3_inputs)[2] = &(c->v11);
    (c->f3).inputs = c->f3_inputs;
    (c->f3).num_of_outputs = 1;
    (c->f3_outputs)[0] = &(c->v12);
    (c->f3).outputs = c->f3_outputs;
    (c->f3).local_context = c->f3_local_context;
    (c->f3_local_context)->base_axis = 1;
    rt_list_t arg_f3_pad;
    arg_f3_pad.size = 2;
    arg_f3_pad.data = c->f3_local_context_shape_pad;
    arg_f3_pad.data[0] = 1;
    arg_f3_pad.data[1] = 1;
    (c->f3_local_context)->pad = arg_f3_pad;
    rt_list_t arg_f3_stride;
    arg_f3_stride.size = 2;
    arg_f3_stride.data = c->f3_local_context_shape_stride;
    arg_f3_stride.data[0] = 1;
    arg_f3_stride.data[1] = 1;
    (c->f3_local_context)->stride = arg_f3_stride;
    rt_list_t arg_f3_dilation;
    arg_f3_dilation.size = 2;
    arg_f3_dilation.data = c->f3_local_context_shape_dilation;
    arg_f3_dilation.data[0] = 1;
    arg_f3_dilation.data[1] = 1;
    (c->f3_local_context)->dilation = arg_f3_dilation;
    (c->f3_local_context)->group = 1;
    (c->f3_local_context)->channel_last = 0;
    allocate_convolution_local_context(&(c->f3));
    // BatchNormalization
    c->f4_local_context = malloc(sizeof(batch_normalization_local_context_t));
    (c->f4).num_of_inputs = 5;
    (c->f4_inputs)[0] = &(c->v12);
    (c->f4_inputs)[1] = &(c->v13);
    (c->f4_inputs)[2] = &(c->v14);
    (c->f4_inputs)[3] = &(c->v15);
    (c->f4_inputs)[4] = &(c->v16);
    (c->f4).inputs = c->f4_inputs;
    (c->f4).num_of_outputs = 1;
    (c->f4_outputs)[0] = &(c->v17);
    (c->f4).outputs = c->f4_outputs;
    (c->f4).local_context = c->f4_local_context;
    rt_list_t arg_f4_axes;
    arg_f4_axes.size = 1;
    arg_f4_axes.data = c->f4_local_context_shape_axes;
    arg_f4_axes.data[0] = 1;
    (c->f4_local_context)->axes = arg_f4_axes;
    (c->f4_local_context)->decay_rate = 0.8999999761581421;
    (c->f4_local_context)->eps = 9.999999747378752e-06;
    (c->f4_local_context)->batch_stat = 1;
    allocate_batch_normalization_local_context(&(c->f4));
    // Tanh
    (c->f5).num_of_inputs = 1;
    (c->f5_inputs)[0] = &(c->v17);
    (c->f5).inputs = c->f5_inputs;
    (c->f5).num_of_outputs = 1;
    (c->f5_outputs)[0] = &(c->v18);
    (c->f5).outputs = c->f5_outputs;
    (c->f5).local_context = 0;
    allocate_tanh_local_context(&(c->f5));
    // AveragePooling
    c->f6_local_context = malloc(sizeof(average_pooling_local_context_t));
    (c->f6).num_of_inputs = 1;
    (c->f6_inputs)[0] = &(c->v18);
    (c->f6).inputs = c->f6_inputs;
    (c->f6).num_of_outputs = 1;
    (c->f6_outputs)[0] = &(c->v19);
    (c->f6).outputs = c->f6_outputs;
    (c->f6).local_context = c->f6_local_context;
    rt_list_t arg_f6_kernel;
    arg_f6_kernel.size = 2;
    arg_f6_kernel.data = c->f6_local_context_shape_kernel;
    arg_f6_kernel.data[0] = 2;
    arg_f6_kernel.data[1] = 2;
    (c->f6_local_context)->kernel = arg_f6_kernel;
    rt_list_t arg_f6_stride;
    arg_f6_stride.size = 2;
    arg_f6_stride.data = c->f6_local_context_shape_stride;
    arg_f6_stride.data[0] = 2;
    arg_f6_stride.data[1] = 2;
    (c->f6_local_context)->stride = arg_f6_stride;
    (c->f6_local_context)->ignore_border = 1;
    rt_list_t arg_f6_pad;
    arg_f6_pad.size = 2;
    arg_f6_pad.data = c->f6_local_context_shape_pad;
    arg_f6_pad.data[0] = 0;
    arg_f6_pad.data[1] = 0;
    (c->f6_local_context)->pad = arg_f6_pad;
    (c->f6_local_context)->channel_last = 0;
    (c->f6_local_context)->including_pad = 1;
    allocate_average_pooling_local_context(&(c->f6));
    // Affine
    c->f7_local_context = malloc(sizeof(affine_local_context_t));
    (c->f7).num_of_inputs = 3;
    (c->f7_inputs)[0] = &(c->v19);
    (c->f7_inputs)[1] = &(c->v20);
    (c->f7_inputs)[2] = &(c->v21);
    (c->f7).inputs = c->f7_inputs;
    (c->f7).num_of_outputs = 1;
    (c->f7_outputs)[0] = &(c->v22);
    (c->f7).outputs = c->f7_outputs;
    (c->f7).local_context = c->f7_local_context;
    (c->f7_local_context)->base_axis = 1;
    allocate_affine_local_context(&(c->f7));
    // Tanh
    (c->f8).num_of_inputs = 1;
    (c->f8_inputs)[0] = &(c->v22);
    (c->f8).inputs = c->f8_inputs;
    (c->f8).num_of_outputs = 1;
    (c->f8_outputs)[0] = &(c->v23);
    (c->f8).outputs = c->f8_outputs;
    (c->f8).local_context = 0;
    allocate_tanh_local_context(&(c->f8));
    // Affine
    c->f9_local_context = malloc(sizeof(affine_local_context_t));
    (c->f9).num_of_inputs = 3;
    (c->f9_inputs)[0] = &(c->v23);
    (c->f9_inputs)[1] = &(c->v24);
    (c->f9_inputs)[2] = &(c->v25);
    (c->f9).inputs = c->f9_inputs;
    (c->f9).num_of_outputs = 1;
    (c->f9_outputs)[0] = &(c->v26);
    (c->f9).outputs = c->f9_outputs;
    (c->f9).local_context = c->f9_local_context;
    (c->f9_local_context)->base_axis = 1;
    allocate_affine_local_context(&(c->f9));
    return (void*)c;
}

int nnablart_validation_free_context(void* context)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;

    for (int i = 0; i < 2; i++) {
        free(c->buffer_pool[i]);
    }
    if(c->variable_buffers_allocate_type[1] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[0]);
    }
    if(c->variable_buffers_allocate_type[2] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[1]);
    }
    if(c->variable_buffers_allocate_type[4] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[2]);
    }
    if(c->variable_buffers_allocate_type[5] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[3]);
    }
    if(c->variable_buffers_allocate_type[6] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[4]);
    }
    if(c->variable_buffers_allocate_type[7] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[5]);
    }
    if(c->variable_buffers_allocate_type[10] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[6]);
    }
    if(c->variable_buffers_allocate_type[11] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[7]);
    }
    if(c->variable_buffers_allocate_type[13] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[8]);
    }
    if(c->variable_buffers_allocate_type[14] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[9]);
    }
    if(c->variable_buffers_allocate_type[15] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[10]);
    }
    if(c->variable_buffers_allocate_type[16] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[11]);
    }
    if(c->variable_buffers_allocate_type[20] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[12]);
    }
    if(c->variable_buffers_allocate_type[21] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[13]);
    }
    if(c->variable_buffers_allocate_type[24] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[14]);
    }
    if(c->variable_buffers_allocate_type[25] == RT_BUFFER_ALLOCATE_TYPE_MALLOC) {
        free(c->param_pool[15]);
    }
    free_convolution_local_context(&(c->f0));
    if (c->f0.local_context != 0) {
        rt_free_func(c->f0.local_context);
        c->f0.local_context = 0;
    }
    free_batch_normalization_local_context(&(c->f1));
    if (c->f1.local_context != 0) {
        rt_free_func(c->f1.local_context);
        c->f1.local_context = 0;
    }
    free_tanh_local_context(&(c->f2));
    if (c->f2.local_context != 0) {
        rt_free_func(c->f2.local_context);
        c->f2.local_context = 0;
    }
    free_convolution_local_context(&(c->f3));
    if (c->f3.local_context != 0) {
        rt_free_func(c->f3.local_context);
        c->f3.local_context = 0;
    }
    free_batch_normalization_local_context(&(c->f4));
    if (c->f4.local_context != 0) {
        rt_free_func(c->f4.local_context);
        c->f4.local_context = 0;
    }
    free_tanh_local_context(&(c->f5));
    if (c->f5.local_context != 0) {
        rt_free_func(c->f5.local_context);
        c->f5.local_context = 0;
    }
    free_average_pooling_local_context(&(c->f6));
    if (c->f6.local_context != 0) {
        rt_free_func(c->f6.local_context);
        c->f6.local_context = 0;
    }
    free_affine_local_context(&(c->f7));
    if (c->f7.local_context != 0) {
        rt_free_func(c->f7.local_context);
        c->f7.local_context = 0;
    }
    free_tanh_local_context(&(c->f8));
    if (c->f8.local_context != 0) {
        rt_free_func(c->f8.local_context);
        c->f8.local_context = 0;
    }
    free_affine_local_context(&(c->f9));
    if (c->f9.local_context != 0) {
        rt_free_func(c->f9.local_context);
        c->f9.local_context = 0;
    }  
    free(context);
    return NN_ERROR_CODE_NOERROR;
}

float* nnablart_validation_input_buffer(void* context, int index)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    switch(index) {
        case 0: return (c->v0).data;
    }
    return 0;
}

float* nnablart_validation_output_buffer(void* context, int index)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    switch(index) {
        case 0: return (c->v26).data;
    }

    return 0;
}
float* nnablart_validation_param_buffer(void* context, int index)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    switch(index) {
        case 0: return (c->v24).data;
        case 1: return (c->v25).data;
        case 2: return (c->v4).data;
        case 3: return (c->v5).data;
        case 4: return (c->v6).data;
        case 5: return (c->v7).data;
        case 6: return (c->v1).data;
        case 7: return (c->v2).data;
        case 8: return (c->v13).data;
        case 9: return (c->v14).data;
        case 10: return (c->v15).data;
        case 11: return (c->v16).data;
        case 12: return (c->v10).data;
        case 13: return (c->v11).data;
        case 14: return (c->v20).data;
        case 15: return (c->v21).data;
    }
    return 0;
}
int nnablart_validation_inference(void* context)
{
    nnablart_validation_local_context_t* c = (nnablart_validation_local_context_t*)context;
    exec_convolution(&(c->f0));
    exec_batch_normalization(&(c->f1));
    exec_tanh(&(c->f2));
    exec_convolution(&(c->f3));
    exec_batch_normalization(&(c->f4));
    exec_tanh(&(c->f5));
    exec_average_pooling(&(c->f6));
    exec_affine(&(c->f7));
    exec_tanh(&(c->f8));
    exec_affine(&(c->f9));
    return NN_ERROR_CODE_NOERROR;
}
