# Generated by Django 2.2 on 2020-02-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PIN',
            fields=[
                ('PINid', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=100)),
                ('rocation_n', models.IntegerField()),
                ('rocation_w', models.IntegerField()),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
