version: '3'  # Docker Composeのバージョン
services:
  web:  # コンテナに名前をつける
    build: .  # Dockerfileがあるディレクトリへのパス
    volumes:
      - ./manager_project:/code  # ホストPCのカレントディレクトリとコンテナ内のcodeディレクトリを同期させる
    ports:
      - "8000:8000"
    command: python manage.py runserver